//Type your code here
var SERVICE_NAME = "CertiServicesJson";
var GET_CATEGORIES = "getCategories";
var GET_PRODUCTS_BY_CATEGORY = "getProductsByCategory";
var GET_PRODUCTS_BY_SEARCH_TEXT = "productSearch";
var GET_PRODUCT_DETAIL = "getProductDetail";
var GET_PRODUCT_REVIEWS = "getProductReviews";
var ID_ROOT_CATEGORY = "cat00000";
var HOME = "Home";